repos:
  - repo: local
    hooks:
      - id: turbo
        name: turbo
        entry: "turbo"
        args: [ "lint", "type-check" ]
        language: system
        pass_filenames: false
        files: \.(js|ts|tsx|json|yaml|yml|md|html|css|scss)$
      - id: format
        name: format
        entry: "pnpm"
        args: [ "run", "format" ]
        language: system
        pass_filenames: false
        files: \.(js|ts|tsx|json|yaml|yml|md|html|css|scss)$
